"""
Generates Pull Request titles, descriptions, and metadata.
"""

import logging
from typing import List

# Import from parent package
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from src.agent.analyzer import FailureClassification
from ..models import FixProposal

logger = logging.getLogger(__name__)


class PRCreator:
    """Creates PR content and metadata"""
    
    def generate_pr_title(self, classification: FailureClassification) -> str:
        """
        Generate PR title.
        
        Args:
            classification: Failure classification
            
        Returns:
            PR title string
        """
        test_name = classification.test_name.split('.')[-1]
        classification_type = classification.classification
        
        if classification_type == "PRODUCT_CHANGE":
            prefix = "🔄 Update test for product change"
        elif classification_type == "AUTOMATION_ISSUE":
            prefix = "🔧 Fix automation issue"
        else:
            prefix = "🤖 Auto-fix"
        
        return f"{prefix}: {test_name}"
    
    def generate_pr_body(
        self,
        classification: FailureClassification,
        fix_proposal: FixProposal
    ) -> str:
        """
        Generate PR description.
        
        Args:
            classification: Failure classification
            fix_proposal: Proposed fix
            
        Returns:
            PR body markdown
        """
        body = f"""## 🤖 Automated Fix

This PR was automatically generated by the AI QA Agent to fix a failing test.

### 📋 Test Information
- **Test Name**: `{classification.test_name}`
- **Classification**: {classification.classification}
- **Confidence**: {classification.confidence}

### 🔍 Root Cause
{classification.root_cause}

### 💡 Recommended Action
{classification.recommended_action}

### 🛠️ Changes Made
{fix_proposal.explanation}

### ✅ Fix Confidence
**{fix_proposal.confidence}**

---

### 📝 Review Checklist
- [ ] Review the code changes
- [ ] Verify the fix addresses the root cause
- [ ] Run the test locally to confirm it passes
- [ ] Check for any side effects on related tests

### 🤝 Next Steps
1. Review the automated fix
2. Run tests locally or in CI
3. Merge if tests pass and fix looks good
4. Close with feedback if fix needs adjustment

---

*Generated by AI QA Agent* 🤖
"""
        return body
    
    def determine_labels(self, classification: FailureClassification) -> List[str]:
        """
        Determine appropriate labels for the PR.
        
        Args:
            classification: Failure classification
            
        Returns:
            List of label names
        """
        labels = ["automated-fix", "qa"]
        
        if classification.classification == "PRODUCT_CHANGE":
            labels.append("product-change")
        elif classification.classification == "AUTOMATION_ISSUE":
            labels.append("automation-issue")
        
        if classification.confidence == "HIGH":
            labels.append("high-confidence")
        elif classification.confidence == "LOW":
            labels.append("needs-review")
        
        return labels
    
    def suggest_reviewers(self, test_file: str) -> List[str]:
        """
        Suggest reviewers based on test file (placeholder for future enhancement).
        
        Args:
            test_file: Path to test file
            
        Returns:
            List of reviewer usernames
        """
        # Future: Use git blame or CODEOWNERS to suggest reviewers
        return []
